# Generated by Django 4.0.3 on 2022-08-04 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='automobilevo',
            old_name='car_name',
            new_name='name',
        ),
    ]
