# Generated by Django 4.0.3 on 2022-08-04 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0004_rename_automobile_salesrecord_vin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesrecord',
            name='vin',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='sales_rest.automobilevo'),
        ),
    ]
